name: Deploy Frontend to Oracle VM

concurrency: 
  group: production
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy Frontend to Oracle VM
      run: |
        ssh -o StrictHostKeyChecking=no dio@192.168.0.6 'bash -s' << 'EOF'
          cd /fastrip/frontend || { echo "Failed to change directory to /fastrip/frontend"; exit 1; }
          if ! git diff-index --quiet HEAD --; then
              git add .
              git commit -m "Automated commit before merging changes"
          fi
          git fetch origin
          git merge origin/master || { echo "Merge failed"; exit 1; }
          npm install || { echo "Failed to install dependencies"; exit 1; }
          npm run build || { echo "Build failed"; exit 1; }
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S cp -r dist/* /var/www/dist || { echo "Failed to copy files"; exit 1; }
        EOF
