name: Deploy Frontend to Oracle VM

concurrency: 
  group: production
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy Frontend to Oracle VM
      run: |
        ssh -o StrictHostKeyChecking=no dio@192.168.0.6 'bash -s' << 'EOF'
          export SUDO_PASSWORD="${{ secrets.SUDO_PASSWORD }}"
          /fastrip/deploy/deploy_front.sh
        EOF
